@Server_HostAddress = https://localhost:64795

GET {{Server_HostAddress}}/api/weatherforecast/ HTTP/1.1
Accept: application/json

###

GET {{Server_HostAddress}}/api/products/
Accept: application/json