/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createUntypedNodeFromDiscriminatorValue, type AdditionalDataHolder, type ApiError, type DateOnly, type Parsable, type ParseNode, type SerializationWriter, type UntypedNode } from '@microsoft/kiota-abstractions';

export interface BasketDTO extends AdditionalDataHolder, Parsable {
    /**
     * The buyerId property
     */
    buyerId?: string | null;
    /**
     * The id property
     */
    id?: UntypedNode | null;
    /**
     * The items property
     */
    items?: BasketItemDTO[] | null;
}
export interface BasketItemDTO extends AdditionalDataHolder, Parsable {
    /**
     * The id property
     */
    id?: UntypedNode | null;
    /**
     * The product property
     */
    product?: ProductDTO | null;
    /**
     * The quantity property
     */
    quantity?: UntypedNode | null;
    /**
     * The totalPrice property
     */
    totalPrice?: UntypedNode | null;
    /**
     * The unitDiscount property
     */
    unitDiscount?: UntypedNode | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {BasketDTO}
 */
// @ts-ignore
export function createBasketDTOFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoBasketDTO;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {BasketItemDTO}
 */
// @ts-ignore
export function createBasketItemDTOFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoBasketItemDTO;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ProblemDetails}
 */
// @ts-ignore
export function createProblemDetailsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoProblemDetails;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ProductDTO}
 */
// @ts-ignore
export function createProductDTOFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoProductDTO;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {WeatherForecast}
 */
// @ts-ignore
export function createWeatherForecastFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoWeatherForecast;
}
/**
 * The deserialization information for the current model
 * @param BasketDTO The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoBasketDTO(basketDTO: Partial<BasketDTO> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "buyerId": n => { basketDTO.buyerId = n.getStringValue(); },
        "id": n => { basketDTO.id = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "items": n => { basketDTO.items = n.getCollectionOfObjectValues<BasketItemDTO>(createBasketItemDTOFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param BasketItemDTO The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoBasketItemDTO(basketItemDTO: Partial<BasketItemDTO> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { basketItemDTO.id = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "product": n => { basketItemDTO.product = n.getObjectValue<ProductDTO>(createProductDTOFromDiscriminatorValue); },
        "quantity": n => { basketItemDTO.quantity = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "totalPrice": n => { basketItemDTO.totalPrice = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "unitDiscount": n => { basketItemDTO.unitDiscount = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param ProblemDetails The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoProblemDetails(problemDetails: Partial<ProblemDetails> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "detail": n => { problemDetails.detail = n.getStringValue(); },
        "instance": n => { problemDetails.instance = n.getStringValue(); },
        "status": n => { problemDetails.status = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "title": n => { problemDetails.title = n.getStringValue(); },
        "type": n => { problemDetails.type = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param ProductDTO The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoProductDTO(productDTO: Partial<ProductDTO> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "description": n => { productDTO.description = n.getStringValue(); },
        "id": n => { productDTO.id = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "image": n => { productDTO.image = n.getStringValue(); },
        "name": n => { productDTO.name = n.getStringValue(); },
        "price": n => { productDTO.price = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param WeatherForecast The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoWeatherForecast(weatherForecast: Partial<WeatherForecast> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "date": n => { weatherForecast.date = n.getDateOnlyValue(); },
        "summary": n => { weatherForecast.summary = n.getStringValue(); },
        "temperatureC": n => { weatherForecast.temperatureC = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
        "temperatureF": n => { weatherForecast.temperatureF = n.getObjectValue<UntypedNode>(createUntypedNodeFromDiscriminatorValue); },
    }
}
export interface ProblemDetails extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The status property
     */
    status?: UntypedNode | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
export interface ProductDTO extends AdditionalDataHolder, Parsable {
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The id property
     */
    id?: UntypedNode | null;
    /**
     * The image property
     */
    image?: string | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The price property
     */
    price?: UntypedNode | null;
}
/**
 * Serializes information the current object
 * @param BasketDTO The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeBasketDTO(writer: SerializationWriter, basketDTO: Partial<BasketDTO> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!basketDTO || isSerializingDerivedType) { return; }
    writer.writeStringValue("buyerId", basketDTO.buyerId);
    writer.writeObjectValue("id", basketDTO.id);
    writer.writeCollectionOfObjectValues<BasketItemDTO>("items", basketDTO.items, serializeBasketItemDTO);
    writer.writeAdditionalData(basketDTO.additionalData);
}
/**
 * Serializes information the current object
 * @param BasketItemDTO The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeBasketItemDTO(writer: SerializationWriter, basketItemDTO: Partial<BasketItemDTO> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!basketItemDTO || isSerializingDerivedType) { return; }
    writer.writeObjectValue("id", basketItemDTO.id);
    writer.writeObjectValue<ProductDTO>("product", basketItemDTO.product, serializeProductDTO);
    writer.writeObjectValue("quantity", basketItemDTO.quantity);
    writer.writeObjectValue("totalPrice", basketItemDTO.totalPrice);
    writer.writeObjectValue("unitDiscount", basketItemDTO.unitDiscount);
    writer.writeAdditionalData(basketItemDTO.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ProblemDetails The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeProblemDetails(writer: SerializationWriter, problemDetails: Partial<ProblemDetails> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!problemDetails || isSerializingDerivedType) { return; }
    writer.writeStringValue("detail", problemDetails.detail);
    writer.writeStringValue("instance", problemDetails.instance);
    writer.writeObjectValue("status", problemDetails.status);
    writer.writeStringValue("title", problemDetails.title);
    writer.writeStringValue("type", problemDetails.type);
    writer.writeAdditionalData(problemDetails.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ProductDTO The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeProductDTO(writer: SerializationWriter, productDTO: Partial<ProductDTO> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!productDTO || isSerializingDerivedType) { return; }
    writer.writeStringValue("description", productDTO.description);
    writer.writeObjectValue("id", productDTO.id);
    writer.writeStringValue("image", productDTO.image);
    writer.writeStringValue("name", productDTO.name);
    writer.writeObjectValue("price", productDTO.price);
    writer.writeAdditionalData(productDTO.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param WeatherForecast The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeWeatherForecast(writer: SerializationWriter, weatherForecast: Partial<WeatherForecast> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!weatherForecast || isSerializingDerivedType) { return; }
    writer.writeDateOnlyValue("date", weatherForecast.date);
    writer.writeStringValue("summary", weatherForecast.summary);
    writer.writeObjectValue("temperatureC", weatherForecast.temperatureC);
    writer.writeObjectValue("temperatureF", weatherForecast.temperatureF);
    writer.writeAdditionalData(weatherForecast.additionalData);
}
export interface WeatherForecast extends AdditionalDataHolder, Parsable {
    /**
     * The date property
     */
    date?: DateOnly | null;
    /**
     * The summary property
     */
    summary?: string | null;
    /**
     * The temperatureC property
     */
    temperatureC?: UntypedNode | null;
    /**
     * The temperatureF property
     */
    temperatureF?: UntypedNode | null;
}
/* tslint:enable */
/* eslint-enable */
