/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { Item_EscapedRequestBuilderRequestsMetadata, type Item_EscapedRequestBuilder } from './item_Escaped/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/Basket/{basketId}
 */
export interface WithBasketItemRequestBuilder extends BaseRequestBuilder<WithBasketItemRequestBuilder> {
    /**
     * The item property
     */
    get item(): Item_EscapedRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithBasketItemRequestBuilderUriTemplate = "{+baseurl}/api/Basket/{basketId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithBasketItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithBasketItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    item: {
        requestsMetadata: Item_EscapedRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
