/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { BasketRequestBuilderNavigationMetadata, BasketRequestBuilderRequestsMetadata, type BasketRequestBuilder } from './basket/index.js';
// @ts-ignore
import { ProductsRequestBuilderRequestsMetadata, type ProductsRequestBuilder } from './products/index.js';
// @ts-ignore
import { type WeatherforecastRequestBuilder, WeatherforecastRequestBuilderRequestsMetadata } from './weatherforecast/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api
 */
export interface ApiRequestBuilder extends BaseRequestBuilder<ApiRequestBuilder> {
    /**
     * The Basket property
     */
    get basket(): BasketRequestBuilder;
    /**
     * The Products property
     */
    get products(): ProductsRequestBuilder;
    /**
     * The weatherforecast property
     */
    get weatherforecast(): WeatherforecastRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ApiRequestBuilderUriTemplate = "{+baseurl}/api";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ApiRequestBuilderNavigationMetadata: Record<Exclude<keyof ApiRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    basket: {
        requestsMetadata: BasketRequestBuilderRequestsMetadata,
        navigationMetadata: BasketRequestBuilderNavigationMetadata,
    },
    products: {
        requestsMetadata: ProductsRequestBuilderRequestsMetadata,
    },
    weatherforecast: {
        requestsMetadata: WeatherforecastRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
