/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBasketDTOFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, type BasketDTO, type ProblemDetails } from '../../models/index.js';
// @ts-ignore
import { type WithBasketItemRequestBuilder, WithBasketItemRequestBuilderNavigationMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/Basket
 */
export interface BasketRequestBuilder extends BaseRequestBuilder<BasketRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.Basket.item collection
     * @param basketId Unique identifier of the item
     * @returns {WithBasketItemRequestBuilder}
     */
     byBasketId(basketId: string) : WithBasketItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     */
     delete(requestConfiguration?: RequestConfiguration<BasketRequestBuilderDeleteQueryParameters> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<BasketDTO>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<BasketRequestBuilderGetQueryParameters> | undefined) : Promise<BasketDTO | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<BasketDTO>}
     * @throws {ProblemDetails} error when the service returns a 400 status code
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<BasketDTO | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<BasketRequestBuilderDeleteQueryParameters> | undefined) : RequestInformation;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<BasketRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
export interface BasketRequestBuilderDeleteQueryParameters {
    basketId?: string;
}
export interface BasketRequestBuilderGetQueryParameters {
    basketId?: string;
}
/**
 * Uri template for the request builder.
 */
export const BasketRequestBuilderUriTemplate = "{+baseurl}/api/Basket{?basketId*}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const BasketRequestBuilderNavigationMetadata: Record<Exclude<keyof BasketRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byBasketId: {
        navigationMetadata: WithBasketItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["basketId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const BasketRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: BasketRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
    },
    get: {
        uriTemplate: BasketRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createBasketDTOFromDiscriminatorValue,
    },
    post: {
        uriTemplate: BasketRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createBasketDTOFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
